packages:
  - "apps/*"
  - "packages/*"

# Define catalogs for shared dependencies to improve performance
catalog:
  # Core React ecosystem
  react: 19.1.1
  react-dom: 19.1.1
  next: 15.3.5
  
  # TypeScript and types
  typescript: 5.9.2
  "@types/node": 22.15.21
  "@types/react": 19.1.5
  "@types/react-dom": 19.1.5
  
  # Form handling
  "@hookform/resolvers": 5.1.1
  react-hook-form: 7.60.0
  zod: 3.25.76
  
  # Data fetching and state
  "@tanstack/react-query": 5.81.5
  "@tanstack/react-query-devtools": 5.81.5
  
  # UI Libraries
  "@yamada-ui/react": 1.7.8
  "@yamada-ui/lucide": 1.10.5
  "@yamada-ui/calendar": 1.8.18
  "@yamada-ui/carousel": 2.1.13
  "@yamada-ui/table": 1.3.15
  
  # Utilities
  dayjs: 1.11.18
  http-status-codes: 2.3.0
  nuqs: 2.4.3
  
  # Development tools
  cross-env: 7.0.3