import { Footer } from "@/components/Footer"
import { QueryProvider, UIProvider } from "@repo/ui/providers"
import { ColorModeScript } from "@yamada-ui/react"
import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"

const geistSans = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
})

const geistMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-geist-mono",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable}`} suppressHydrationWarning>
        <QueryProvider>
          <ColorModeScript initialColorMode="dark" />
          <UIProvider>
            {children}
            <Footer />
          </UIProvider>
        </QueryProvider>
      </body>
    </html>
  )
}
