name: Comment
description: Leaves a comment with relevant preview information

inputs:
  preview-storybook:
    description: The URL of the storybook preview
    required: true
  preview-frontend:
    description: The URL of the frontend preview
    required: true

runs:
  using: composite
  steps:
    - name: Find Comment
      uses: peter-evans/find-comment@v2
      if: github.event_name == 'pull_request'
      id: find-comment
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: 'github-actions[bot]'
        body-includes: Preview Deployment Status
        direction: last

    - name: Create or update comment
      uses: peter-evans/create-or-update-comment@v3
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-id: ${{ steps.find-comment.outputs.comment-id }}
        edit-mode: replace
        body: |
          ## Preview Deployment Status

          ✅ Storybook deployment successful!
          URL: ${{ inputs.preview-storybook }}

          ✅ Frontend deployment successful!
          URL: ${{ inputs.preview-frontend }}
