name: Comment
description: Leaves a comment with relevant preview information

inputs:
  preview-storybook:
    description: The URL of the storybook preview
    required: false
  preview-frontend:
    description: The URL of the frontend preview
    required: false
  method:
    description: The method to use for creating or updating the comment
    required: true

runs:
  using: composite
  steps:
    - name: Find Comment
      uses: peter-evans/find-comment@v2
      if: github.event_name == 'pull_request'
      id: find-comment
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: 'github-actions[bot]'
        body-includes: Preview Deployment Status
        direction: last

    - name: Pre-comment
      if: ${{ inputs.method == 'pre' }}
      uses: peter-evans/create-or-update-comment@v3
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-id: ${{ steps.find-comment.outputs.comment-id }}
        edit-mode: replace
        body: |
          ## Preview Deployment Status

          🔄 Storybook Preview: Deploying...

          🔄 Frontend Preview: Deploying...

    - name: Create message
      id: create-message
      if: ${{ inputs.method == 'post' }}
      shell: bash
      run: |
        message="${{ steps.find-comment.outputs.comment-body }}"

        if [[ -n "${{ inputs.preview-storybook }}" ]]; then
          message=$(echo "$message" | sed "s|🔄 Storybook Preview: Deploying...|✅ Storybook Preview: ${{ inputs.preview-storybook }}|")
        fi

        if [[ -n "${{ inputs.preview-frontend }}" ]]; then
          message=$(echo "$message" | sed "s|🔄 Frontend Preview: Deploying...|✅ Frontend Preview: ${{ inputs.preview-frontend }}|")
        fi

        echo "message<<EOF" >> $GITHUB_OUTPUT
        echo "$message" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Post-comment
      if: ${{ inputs.method == "post" }}
      uses: peter-evans/create-or-update-comment@v3
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-id: ${{ steps.find-comment.outputs.comment-id }}
        edit-mode: replace
        body: |
          ${{ steps.create-message.outputs.message }}
