name: "Build Backend"
description: "This workflow checks if the backend builds are working correctly."

inputs:
  PAYLOAD_SECRET:
    description: "The payload secret for the workspace."
    required: true
  DATABASE_URI:
    description: "The database URI for the workspace."
    required: true
  NEXT_PUBLIC_URL:
    description: "The public URL for the workspace."
    required: true
  GOOGLE_CLIENT_ID:
    description: "The Google OAuth client ID."
    required: true
  GOOGLE_CLIENT_SECRET:
    description: "The Google OAuth client secret."
    required: true
  JWT_SECRET:
    description: "The JWT signing secret."
    required: true

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'

    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: latest
        run_install: false

    - name: Restore node_modules cache
      uses: actions/cache/restore@v4
      id: cache
      with:
        path: |
          node_modules
          */node_modules
          packages/*/node_modules
          apps/*/node_modules
        key: ${{ runner.os }}-node_modules-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-node_modules-

    - name: Install dependencies if cache misses
      run: NODE_ENV=production pnpm install --frozen-lockfile --ignore-scripts
      shell: bash

    - name: Restore Next.js cache
      uses: actions/cache@v4
      with:
        path: |
          apps/backend/.next/cache
        key: ${{ runner.os }}-nextjs-backend-${{ hashFiles('apps/backend/*') }}
        restore-keys: |
          ${{ runner.os }}-nextjs-backend

    - name: Build backend
      shell: bash
      env:
        NEXT_PUBLIC_URL: ${{ inputs.NEXT_PUBLIC_URL }}
        PAYLOAD_SECRET: ${{ inputs.PAYLOAD_SECRET }}
        DATABASE_URI: ${{ inputs.DATABASE_URI }}
        GOOGLE_CLIENT_ID: ${{ inputs.GOOGLE_CLIENT_ID }}
        GOOGLE_CLIENT_SECRET: ${{ inputs.GOOGLE_CLIENT_SECRET }}
        JWT_SECRET: ${{ inputs.JWT_SECRET }}
      run: pnpm turbo run build --filter backend
