name: "Vitest Coverage"
description: "Run Vitest coverage, compare with master, and comment on PR"

inputs:
  pr-number:
    description: "Pull request number"
    required: true
  github-token:
    description: "GitHub token"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout master branch
      uses: actions/checkout@v4
      with:
        ref: master
        fetch-depth: 2

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'
    
    - name: Enable Corepack
      run: corepack enable
      shell: bash

    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: latest
        run_install: false

    - name: Restore Turborepo cache
      uses: actions/cache@v4
      with:
        path: |
          .turbo
          node_modules
          */node_modules
          packages/*/node_modules
          apps/*/node_modules
        key: ${{ runner.os }}-turbo-coverage-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-turbo-coverage-

    - name: Download Local Coverage
      uses: actions/download-artifact@v4
      with:
        name: local-coverage
        path: coverage

    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash

    - name: Run Coverage (master)
      run: |
        mkdir -p coverage
        pnpm test:coverage
      shell: bash

    - name: Upload Master Coverage Artifact
      uses: actions/upload-artifact@v4
      with:
        name: master-coverage
        path: coverage/

    - name: Download Master Coverage
      uses: actions/download-artifact@v4
      with:
        name: master-coverage
        path: .master-coverage

    - name: Compare PR and Master Coverage
      id: pr-line-coverage
      run: |
        # Check if master coverage directory exists and is not empty
        if [ ! -d ".master-coverage" ] || [ -z "$(ls -A .master-coverage)" ]; then
          echo "Error: Master coverage artifact is missing or empty."
          exit 1
        fi

        # Extract master and PR coverage
        master_total=$(pnpm nyc report --temp-dir .master-coverage --reporter=text-summary | grep -oP 'Lines\s+:\s+\K[\d.]+')
        pr_total=$(pnpm nyc report --temp-dir coverage --reporter=text-summary | grep -oP 'Lines\s+:\s+\K[\d.]+')

        # Validate extracted values
        if [ -z "$master_total" ] || [ -z "$pr_total" ]; then
          echo "Error: Failed to extract coverage data. master_total='$master_total', pr_total='$pr_total'"
          exit 1
        fi

        diff=$(echo "scale=2; $pr_total - $master_total" | bc)
        if (( $(echo "$diff >= 0" | bc -l) )); then
          coverage_status="+$diff%"
        else
          coverage_status="$diff%"
        fi
        echo "PR_LINE_COVERAGE=$coverage_status" >> $GITHUB_OUTPUT
      shell: bash

    - name: Generate Overall Coverage Summary
      id: overall-coverage-summary
      run: |
        echo "OVERALL_COVERAGE_SUMMARY<<EOF" >> $GITHUB_OUTPUT
        pnpm nyc report --temp-dir coverage --reporter=text-summary | sed -n '/^=======/,/^$/p' >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
      shell: bash

    - name: Find Previous Coverage Comment
      uses: peter-evans/find-comment@v3
      id: find-comment
      with:
        issue-number: ${{ inputs.pr-number }}
        comment-author: 'github-actions[bot]'
        body-includes: '## Vitest Coverage Report'

    - name: Update Coverage Comment
      uses: peter-evans/create-or-update-comment@v4
      with:
        comment-id: ${{ steps.find-comment.outputs.comment-id }}
        issue-number: ${{ inputs.pr-number }}
        body: |
          ## Vitest Coverage Report

          ### Overall Repository Coverage
          ```
          ${{ steps.overall-coverage-summary.outputs.OVERALL_COVERAGE_SUMMARY }}
          ```

          **PR Coverage: ${{ steps.pr-line-coverage.outputs.PR_LINE_COVERAGE }}** comparing to master branch coverage.

          [View detailed coverage report](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})

          To view detailed coverage locally, run `pnpm test:coverage`.
        edit-mode: replace
        token: ${{ inputs.github-token }}

    - name: Checkout PR branch
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        fetch-depth: 2