name: "Storybook Build"
description: "This workflow builds Storybook for the specified workspace."

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'

    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: latest
        run_install: false

    - name: Restore node_modules cache
      uses: actions/cache/restore@v4
      id: cache
      with:
        path: |
          node_modules
          packages/ui/node_modules
        key: ${{ runner.os }}-node_modules-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-node_modules-

    - name: Install dependencies if cache misses
      if: steps.cache-check.outputs.cache-hit != 'true'
      run: NODE_ENV=production pnpm install --filter @repo/ui --frozen-lockfile
      shell: bash

    - name: Build Storybook for @repo/ui
      shell: bash
      run: pnpm turbo run storybook:build --filter @repo/ui