name: Deploy Preview App
on:
  pull_request:
    types: [opened, reopened, synchronize, closed]
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '.gitignore'

jobs:
  preview_app:
    runs-on: ubuntu-latest
    outputs:
      url: ${{ steps.deploy.outputs.url }}
    concurrency:
      group: pr-${{ github.event.number }}

    env:
      FLY_API_TOKEN: ${{ secrets.FLY_CLIENT_API_TOKEN }}
    environment:
      name: Preview
      url: ${{ steps.deploy.outputs.url }}
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Deploy Preview app to Fly.io
        id: deploy
        uses: superfly/fly-pr-review-apps@1.2.1
        with:
            build-args:
                - "NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}"
                - "NEXT_PUBLIC_URL=${{ secrets.NEXT_PUBLIC_URL }}"
                - "JWT_SECRET=${{ secrets.JWT_SECRET }}"
                - "TURBO_TEAM=${{ vars.TURBO_TEAM }}"
                - "TURBO_TOKEN=${{ secrets.TURBO_TOKEN }}"
