name: Deploy Preview App
on:
  pull_request:
    types: [opened, reopened, synchronize, closed]
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '.gitignore'

env:
  FLY_API_TOKEN: ${{ secrets.FLY_CLIENT_API_TOKEN }}

jobs:
  preview_app:
    runs-on: ubuntu-latest
    outputs:
      url: ${{ steps.deploy.outputs.url }}
    concurrency:
      group: pr-${{ github.event.number }}

    environment:
      name: Preview
      url: ${{ steps.deploy.outputs.url }}
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Deploy Preview app to Fly.io
        id: deploy
        uses: superfly/fly-pr-review-apps@1.2.1
